apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::446394401880:role/eksctl-expense-nodegroup-expense-NodeInstanceRole-xzSOlP4R0hU5
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - groups:
      - default-trainee
      userarn: arn:aws:iam::446394401880:user/Mahi
      username: Mahi
kind: ConfigMap
metadata:
  creationTimestamp: "2026-08-17T05:26:55Z"
  name: aws-auth
  namespace: kube-system
  uid: 36b66c4c-27b6-491c-938d-278f6a3b9d3a
